Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2021-12, with the labels that each got.

#87 Adding a new job for p9 vscsi
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-vscsi-min/Jenkinsfile
Labels: approved, size/L

#88 Updating scg ids
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-ssp-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-vscsi-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p8-vscsi-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-ssp-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.9/daily-ocp4.9-powervm-p8-vscsi-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.9/daily-ocp4.9-powervm-p9-ssp-min/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: approved

#90 Change rhel-84 to rhel-85 for stability checks
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas12-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt02-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-04-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-06-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-montreal01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-tokyo-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-toronto-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-washington-p9-stability-check/Jenkinsfile
Labels: lgtm, approved, size/M

#91 Fix get client and build methods
  vars/getOpenshiftBuild.groovy
  vars/getOpenshiftClient.groovy
  vars/getOpenshiftClientAMD.groovy
Labels: lgtm, approved, size/M
