Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2021-10, with the labels that each got.

#59 Scale logic fix
  jobs/pipelines/powervs/ocp-4.9/daily-ocp4.9-powervs-toronto01-p9-scale/Jenkinsfile
  vars/setupAndRunScaleTest.groovy
Labels: lgtm, approved, size/M

#70 Changing schedule
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min/Jenkinsfile
Labels: approved, size/S

#72 Changing Schedule
  hack/jjb_template.jinja2
Labels: approved, size/M

#74 PowerVS job for ocp4.10
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-toronto01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
Labels: approved, size/L
