Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2021-11, with the labels that each got.

#82 Shifting jobs to montreal region
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-montreal01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-montreal01-p9-scale/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-script-montreal01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-script-montreal01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.9/daily-ocp4.9-powervs-montreal01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  scripts/restore-backup.sh
Labels: lgtm, approved, size/XL

#81 Added job for cleanup resources
  images/ibmcloud-backup-image/Dockerfile
  jobs/pipelines/utility-jobs/powervs-cleanup-job/Jenkinsfile
  scripts/cleanup-powervs-resources.sh
Labels: lgtm, approved, size/M

#83 Update README.md
  README.md
Labels: lgtm, size/XS, approved

#85 Disabling proxy job
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-extproxy-min/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
Labels: lgtm, size/XS, approved
