Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2021-06, with the labels that each got.

#31 Removing registry api.ci.openshift.org
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
Labels: approved, lgtm, size/XS

#32 Fix verify job
  hack/verify-validate-pipelines.sh
Labels: approved, lgtm, size/S

#34 Changing image to rhel-84
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas12-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt02-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-tokyo-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-toronto-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-washington-p9-stability-check/Jenkinsfile
Labels: approved, lgtm, size/S

#33 Initial commit jenkins backup
  README.md
  docs/BACKUP_README.md
  hack/ibmcloud-build-pod.yaml
  hack/jjb_template.jinja2
  images/ibmcloud-backup-image/Dockerfile
  jobs/pipelines/daily-jenkins-backup-job/Jenkinsfile
  jobs/pipelines/restore-backup/Jenkinsfile
  scripts/backup.sh
  scripts/restore-backup.sh
Labels: approved, lgtm, size/L

#35 Change folder structure for backup jobs
  jobs/pipelines/powervs-image-create-and-upload-job/Jenkinsfile
  jobs/pipelines/utility-jobs/daily-jenkins-backup-job/Jenkinsfile
  jobs/pipelines/utility-jobs/restore-backup/Jenkinsfile
Labels: approved, lgtm, size/XS

#36 Fixing Image upload job
  jobs/pipelines/powervs/powervs-image-create-and-upload-job/Jenkinsfile
  scripts/convert-upload-image-powervs.sh
Labels: approved, lgtm, size/XS

#38 Correcting sequence and moving must gather logs
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-powervm-p8-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-powervm-p8-scale/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-powervm-p9-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-powervm-p9-scale/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.5/daily-ocp4.5-to-4.6-powervm-p8-max-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.6/daily-ocp4.6-powervm-p8-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.6/daily-ocp4.6-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.6/daily-ocp4.6-powervm-p9-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.6/daily-ocp4.6-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.6/daily-ocp4.6-to-4.7-powervm-p8-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p8-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p8-min-vscsi/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-max-sriov/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-min-chaos/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-min-extproxy/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-min-ssp/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.7/daily-ocp4.7-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min-chaos/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min-sriov/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-dallas-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-frankfurt01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-london-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-script-saopaulo-01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-script-sydney-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-script-tokyo-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-toronto-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.5/daily-ocp4.5-powervs-washington-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-frankfurt01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-london06-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-script-saopaulo01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-script-sydney-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-script-sydney-p9-scale/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-sydney-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-tokyo-p9-scale/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.6/daily-ocp4.6-powervs-toronto-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-dallas-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-frankfurt01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-frankfurt02-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-london06-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-script-osaka21-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-script-tokyo-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-sydney-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-tokyo-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-tokyo-p9-scale/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.7/daily-ocp4.7-powervs-toronto-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-osaka21-p9-scale/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-tokyo-p9-scale/Jenkinsfile
  scripts/backup.sh
  vars/validateCoStatus.groovy
Labels: approved, lgtm, size/XL

#39 Reverting changes for 4.8 E2e run and changing Go Lang version
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min-sriov/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-dallas12-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-london-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-osaka21-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-saopaulo01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-sydney-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-tokyo-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-toronto-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.8/daily-ocp4.8-powervs-washington-p9-min/Jenkinsfile
Labels: approved, lgtm, size/M
