Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-11, with the labels that each got.

#198 Adding ssp 4.12 Job
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p9-ssp-min/Jenkinsfile
Labels: lgtm, approved, size/L

#197 Adding upgrade z-stream job
  jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  vars/odfRunCommands.groovy
  vars/odfRunSetupScript.groovy
Labels: lgtm, approved, size/L

#138 Creating powervs zstream trigger job and modified old powervm trigger…
  jobs/pipelines/powervm/zstreams/zstream-powervm-trigger-job/Jenkinsfile
  jobs/pipelines/powervs/zstreams/zstream-powervs-trigger-job/Jenkinsfile
Labels: lgtm, approved, size/L, needs-ok-to-test

#199 Adding dump-powers.sh script in IPI jobs and Fixing issue in latest sydney job
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-script-sydney05-p9-latest/Jenkinsfile
Labels: lgtm, approved, size/S

#200 Removing ssh connection in ansible config
  vars/runOvnCniValidation.groovy
  vars/setupAndRunE2e.groovy
Labels: lgtm, approved, size/S

#201 Changing image of IPI jobs
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/S

#202 Correcting vpc region for montreal
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
Labels: lgtm, size/XS, approved

#204 Correcting backup job
  docs/BACKUP_README.md
  jobs/pipelines/utility-jobs/daily-jenkins-backup-job/Jenkinsfile
  scripts/create-backup.sh
  scripts/prepare-backup.sh
Labels: lgtm, approved, size/L

#206 Improving the deploy method
  vars/deployCluster.groovy
Labels: lgtm, approved, size/S

#207 Modify verification test job to support ppc64le tags
  scripts/verification.sh
Labels: lgtm, size/XS, approved, needs-ok-to-test

#209 Update setupCommonEnvironmentVariables.groovy
  vars/setupCommonEnvironmentVariables.groovy
Labels: approved

#211 Increased the ssh timeout
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-script-sydney05-p9-smoke/Jenkinsfile
Labels: lgtm, approved

#212 Change scg id and fix small issues
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p10-vscsi-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p9-sriov-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p9-ssp-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.8/daily-ocp4.8-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.9/daily-ocp4.9-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-script-sydney05-p9-latest/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/M

#213 Install necessary plugins for dump script IPI
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/S
