Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-02, with the labels that each got.

#99 Change go lang version for 4.10 jobs
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4.x-powervm-p8-deploy/Jenkinsfile
  jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4.x-powervm-p8-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-ssp-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p8-nova-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-extproxy-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-sriov-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-ssp-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-vscsi-min/Jenkinsfile
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-montreal01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-saopaulo01-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-sydney04-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-toronto01-p9-min/Jenkinsfile
  scripts/convert-upload-image-powervs.sh
Labels: lgtm, approved, size/M

#96 Adding Zstream Automation Jenkinsfiles
  jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
  jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervm/zstreams/zstream-trigger-job/Jenkinsfile
Labels: lgtm, approved, size/XL, ok-to-test

#98 Added Jenkinsfile for two upgrades
  jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4x-p8-min-two-upgrades/Jenkinsfile
  vars/setupAndUpgrade.groovy
Labels: lgtm, approved, size/L, ok-to-test

#101 Z-stream jobs renamed
  jobs/pipelines/powervm/zstreams/zstream-trigger-job/Jenkinsfile
Labels: lgtm, size/XS, approved

#102 Change p9 max to p9 min for powervm job
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p9-min/Jenkinsfile
Labels: lgtm, approved, size/L

#104 Reduce stability job frequency to two
  hack/jjb_template.jinja2
Labels: lgtm, approved, size/S

#105 Removing e2e from Z Stream next upgrade job
  jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
Labels: lgtm, approved, size/S
