Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-10, with the labels that each got.

#166 Add verification test job
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-verification-tests-script-sydney05-p9-min/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  scripts/verification.sh
Labels: lgtm, approved, size/L, needs-ok-to-test

#163 Adding odf 4.12 deployment automation
  deploy/Makefile
  deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  vars/odfAuthYaml.groovy
  vars/odfProcessTierTestResults.groovy
  vars/odfRunCommands.groovy
  vars/odfRunSetupScript.groovy
  vars/setupClusterConfig.groovy
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/XXL

#169 Correcting image files to pick
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
Labels: lgtm, approved

#170 Formatting slack messages
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
  vars/odfAuthYaml.groovy
  vars/odfProcessTierTestResults.groovy
  vars/odfRunSetupScript.groovy
  vars/pullSecret.groovy
Labels: lgtm, approved, size/S

#171 Fix e2e issue
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, size/XS, approved

#173 Fix processor error
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
Labels: lgtm, size/XS, approved

#174 Fix vpc region issue mon
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
Labels: lgtm, size/XS, approved

#177 fixing "client_loop: send disconnect: Broken pipe" issue.
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  vars/odfRunSetupScript.groovy
Labels: lgtm, approved, size/L

#179 Changing systype to s922 for sydney
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-script-sydney05-p9-min/Jenkinsfile
Labels: lgtm, size/XS, approved

#180 Update jjb_template.jinja2
  hack/jjb_template.jinja2
Labels: lgtm, approved, size/S

#181 Changing network provider for 4.12 jobs
  deploy/Makefile
  deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
  deploy/templates/.deploy-openshift4-powervs.tfvars.template
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p10-max/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p10-sdn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-script-sydney05-p9-min/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/M

#182 Moving to s922
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
Labels: lgtm, size/XS, approved

#183 Always get the logs at the end
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  vars/odfRunSetupScript.groovy
Labels: lgtm, approved, size/M

#184 Fixing capturing files and deploy script
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
  vars/deployCluster.groovy
Labels: lgtm, approved, size/S

#185 Fixing artifactory path
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
Labels: lgtm, approved, size/S

#187 increase ipi 4.12 jobs in syd05 and lon06 to 4x daily
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#188 Fixing IPI jobs
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
Labels: lgtm, size/XS, approved

#189 Fixing powervm jobs
  deploy/Makefile
  deploy/templates/.deploy-openshift4-powervc.tfvars.template
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/M

#191 Fixing deploy cluster
  vars/deployCluster.groovy
Labels: lgtm, size/XS, approved

#193 Adding 4.12 Osaka job
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-osaka21/Jenkinsfile
Labels: lgtm, approved, size/L

#194 Disabling 4.11 IPI jobs
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#195 Change playbook version for PowerVS
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, size/XS, approved

#196 avoiding ssp images from default image list
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
Labels: approved, size/S
