Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-07, with the labels that each got.

#127 Adding image import functionality in stability jobs
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas12-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt02-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-04-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-06-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-montreal01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-tokyo-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-toronto-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-washington-p9-stability-check/Jenkinsfile
Labels: lgtm, approved, size/XL

#128 Updating PowerVC custom upgrade jobs
  jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4.x-powervm-upgrade/Jenkinsfile
  jobs/pipelines/powervm/custom-powervm-jobs/custom-ocp4x-powervm-two-upgrades/Jenkinsfile
Labels: lgtm, approved, size/L

#129 Adding custom upgrade jobs for PowerVS
  jobs/pipelines/powervs/custom-powervs-jobs/custom-ocp4x-powervs-sydney04-p9-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/custom-powervs-jobs/custom-ocp4x-powervs-sydney04-p9-min-two-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  vars/setupAndUpgrade.groovy
Labels: lgtm, approved, size/XL

#131 Changing PVSADM_VERSION in poll-powervs-images job
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
Labels: lgtm, size/XS, approved

#133 changing image name in stability jobs
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-dallas12-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-frankfurt02-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-04-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-06-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-montreal01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-osaka21-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-saopaulo01-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-tokyo-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-toronto-p9-stability-check/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-washington-p9-stability-check/Jenkinsfile
Labels: lgtm, approved, size/L

#134 Moving jobs from syd 04
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-sydney04-p9-min/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-sydney-p9-stability-check/Jenkinsfile
Labels: lgtm, approved, size/S
