Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-12, with the labels that each got.

#216 Enabling vault for all Tier tests
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p10-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
Labels: lgtm, approved, size/S

#205 Removing bootstrap node after deployment
  vars/deployCluster.groovy
Labels: lgtm, size/XS, approved

#217 Adding Tier4a job
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4a/Jenkinsfile
Labels: lgtm, approved, size/L

#218 Reverting back bootstrap deletion change
  vars/deployCluster.groovy
Labels: lgtm, size/XS, approved

#219 Adding Bootstrap deletion change
  vars/deployCluster.groovy
Labels: lgtm, size/XS, approved

#220 Removing playbook tag and using default tag
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-sydney04-p9-latest/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-script-sydney05-p9-latest/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/S

#222 Fixing odf build information
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p10-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p10-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p8-powervm-upgrade/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-2/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4a/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-lon06-tier-4b/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-1/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-3/Jenkinsfile
  jobs/pipelines/powervs/odf/4.12/daily-odf4.12-powervs-syd05-tier-4c/Jenkinsfile
  jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  scripts/odf/odf-build-info.sh
  scripts/odf/run-odf-deploy.sh
  scripts/odf/run-odf-upgrade.sh
  scripts/odf/run-tier-tests.sh
  vars/odfProcessTierTestResults.groovy
  vars/odfRunCommands.groovy
Labels: lgtm, approved, size/XL

#225 Removing playbook tag from template
  deploy/templates/.deploy-openshift4-powervc.tfvars.template
  deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
  deploy/templates/.deploy-openshift4-powervs.tfvars.template
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ocp/4.10/daily-ocp4.10-powervs-script-sydney05-p9-min/Jenkinsfile
Labels: lgtm, approved, size/S
