Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-09, with the labels that each got.

#151 Add reboot for powervs
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-sydney05-p9-min/Jenkinsfile
  vars/createIPICluster.groovy
  vars/deployCluster.groovy
  vars/initializeEnvironment.groovy
Labels: lgtm, approved, size/L

#152 Adding credentials for IPI deployment
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
Labels: lgtm, approved, size/S

#153 Updating agent dockerfile
  images/jenkins-inbound-agent/Dockerfile
Labels: lgtm, approved, size/S

#155 Adding ocp4.12 ipi job for london06
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
Labels: lgtm, approved, size/L

#159 Making changes according to the updated json output
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
Labels: lgtm, approved, size/S

#160 Error fix
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
Labels: lgtm, size/XS, approved

#161 Removing printing of id_rsa
  deploy/Makefile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-script-montreal01-p9-scale/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-toronto01-p9-min/Jenkinsfile
Labels: lgtm, approved, size/S

#162 Removing schedule for ssp job
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#165 Add p8 4.12 job
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p8-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-script-montreal01-p9-scale/Jenkinsfile
Labels: lgtm, size/XS, approved
