Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2022-08, with the labels that each got.

#135 Changing Sydney poll image to toronto
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-sydney04-p9-latest/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.10/daily-ocp4.10-powervs-sydney04-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.11/daily-ocp4.11-powervs-sydney04-p9-min/Jenkinsfile
Labels: lgtm, approved, size/S

#132 Adding Z stream jobs for PowerVS
  jobs/pipelines/powervs/zstreams/zstream-ocp4x-powervs-toronto01-p9-current-upgrade/Jenkinsfile
  jobs/pipelines/powervs/zstreams/zstream-ocp4x-powervs-toronto01-p9-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervs/zstreams/zstream-ocp4x-powervs-toronto01-p9-min-next-upgrade/Jenkinsfile
Labels: lgtm, approved, size/XL

#130 Changing upgrade channel for OCP 4.6 Z Stream releases upgrade job
  jobs/pipelines/powervm/zstreams/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
Labels: lgtm, approved, size/S

#136 Move QE custom upgrade jobs from syd04 to osa21
  jobs/pipelines/powervs/custom-powervs-jobs/custom-ocp4x-powervs-osaka21-p9-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/custom-powervs-jobs/custom-ocp4x-powervs-osaka21-p9-min-two-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
Labels: lgtm, approved, size/M

#137 Adding github.ibm.com to known hosts
  vars/cloneRepo.groovy
Labels: lgtm, size/XS, approved

#139 Adding 4.12 job
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.12/daily-ocp4.12-powervm-p10-min/Jenkinsfile
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
  jobs/pipelines/powervs/ocp-4.12/daily-ocp4.12-powervs-london06-p9-min/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  jobs/pipelines/powervs/stability-check/daily-powervs-london-06-p9-stability-check/Jenkinsfile
Labels: lgtm, approved, size/L

#140 Adding IPI deployment
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
  vars/createIPICluster.groovy
Labels: lgtm, approved, size/XL

#141 Changing api key
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
Labels: lgtm, approved, size/S

#144 Fixing errors
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-ovn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p8-ovn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-ovn-min/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi-4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
  vars/cloneRepo.groovy
  vars/runOvnCniValidation.groovy
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/S

#145 Adding 4.12 IPI job
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
  vars/deployCluster.groovy
Labels: lgtm, approved, size/L

#146 Changing Url for Ipi 4.12 deployment
  jobs/pipelines/powervs/ipi-4.12/daily-ipi4.12-powervs-toronto01/Jenkinsfile
Labels: lgtm, size/XS, approved

#149 Updating sleep time
  vars/deployCluster.groovy
Labels: lgtm, approved, size/S

#150 Fix some functionality
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p10-ovn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.10/daily-ocp4.10-powervm-p8-ovn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp-4.11/daily-ocp4.11-powervm-p10-ovn-min/Jenkinsfile
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
Labels: lgtm, approved, size/S
