Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2023-07, with the labels that each got.

#286 Adding rhcos and rhel image for 4.14 in z-stream jobs of odf
  jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
  jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
Labels: lgtm, approved, size/S

#287 enabled 4.13 stable latest build
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-min/Jenkinsfile
Labels: lgtm, approved, size/S

#288 4.14 IPI job schedule changes
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#290 Do not run nodes_config playbook
  deploy/templates/.deploy-openshift4-powervc.tfvars.template
  deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/S

#289 changed 4.14 IPI job basedomain and updated OpenShift-installer latest version
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-sydney05/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/M

#291 created ODF 4.14 OCP jobs
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-4b/Jenkinsfile
  jobs/pipelines/powervm/odf/4.14/daily-odf4.14-powervm-p9-tier-4c/Jenkinsfile
  vars/odfRunSetupScript.groovy
Labels: lgtm, approved, size/XXL

#292 Enabling 4.14 IPI job in Tok04
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-tokyo04-1/Jenkinsfile
Labels: lgtm, approved, size/L

#293 Disabling hypershift CI scheduled job.
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#294 Updating the installer
  vars/setupCommonEnvironmentVariables.groovy
Labels: size/XS, approved
