Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2023-03, with the labels that each got.

#258 Updating cluster config and ODF upgrade script
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
  jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
  scripts/odf/fix-config.sh
  vars/odfRunSetupScript.groovy
  vars/setupClusterConfig.groovy
Labels: lgtm, approved, size/M

#259 Fixing job name
  hack/jjb_template.jinja2
Labels: lgtm, approved, size/S

#260 Change credentials for IPI job
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/M

#261 Temporary changes to change installer binary for IPI jobs
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/M

#263 Enabling vault
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4b/Jenkinsfile
  jobs/pipelines/powervm/odf/4.13/daily-odf4.13-powervm-p9-tier-4c/Jenkinsfile
Labels: lgtm, approved, size/S

#264 Change installer binary to nightly for IPI jobs
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/M

#256 Updating PowerVS Z stream jobs
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-current-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-powervs-trigger-job/Jenkinsfile
  scripts/cleanup-powervs-resources.sh
Labels: lgtm, size/L

#257 Updating PowerVC Z stream jobs
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-powervm-trigger-job/Jenkinsfile
Labels: lgtm, size/M

#262 Store and upload must-gather logs for z stream jobs
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-current-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-min-next-upgrade/Jenkinsfile
  vars/storeMustGatherLogs.groovy
Labels: lgtm, size/M

#265 Change installer binary and removed os installer image for IPI jobs
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/S

#266 Creating CROO job
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-croo/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  scripts/cluster_resource_override_operator_setup_e2e.sh
Labels: lgtm, approved, size/L

#267 Changing rc version for 4.13 and removing default image line for IPI job
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-sydney05/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/M
