Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2023-01, with the labels that each got.

#227 Fix for ec build
  scripts/mirror-images.sh
Labels: lgtm, size/XS, approved

#228 Change build discarder for IPI jobs
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#229 Reduce schedule of PowerVS jobs
  hack/jjb_template.jinja2
Labels: lgtm, approved, size/M

#231 Fixing file paths
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p10-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p10-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p10-tier-4c/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-4b/Jenkinsfile
  jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p8-powervm-upgrade/Jenkinsfile
  jobs/pipelines/powervs/odf/zstreams/zstream-odf4.x-powervs-syd05-upgrade/Jenkinsfile
Labels: lgtm, approved, size/S

#233 Changing openshift installer for IPI jobs
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
Labels: lgtm, approved, size/S

#232 Remove schedule for daily-ocp4.12-powervs-script-sydney05-p9-smoke job
  hack/jjb_template.jinja2
Labels: lgtm, size/XS, approved

#234 Add verification test job on PowerVC
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.12/daily-ocp4.12-powervm-p8-verification/Jenkinsfile
Labels: lgtm, approved, size/L

#235 Create Pipelines in PowerVC for 4.13
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p10-sdn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p10-vscsi/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-sriov/Jenkinsfile
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
Labels: lgtm, approved, size/XL

#237 Fixing small errors
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.9/daily-ocp4.9-to-4.10-powervm-p8-min-upgrade/Jenkinsfile
  jobs/pipelines/powervs/hypershift/daily-ocp4.12-powervs-sydney04-hypershift-e2e/Jenkinsfile
Labels: lgtm, approved, size/S

#236 Change p10 to p9
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-sdn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-vscsi/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-4c/Jenkinsfile
Labels: lgtm, approved, size/M

#239 Fix error
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, size/XS

#240 optimising resource for odf
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-sriov/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-verification/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.12/daily-odf4.12-powervm-p9-tier-4c/Jenkinsfile
  jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p8-powervm-upgrade/Jenkinsfile
  vars/setupClusterConfig.groovy
Labels: lgtm, approved, size/M

#241 Moving odf zstream job to p9_pvm
  jobs/pipelines/powervm/odf/zstreams/zstream-odf4.x-p9-powervm-upgrade/Jenkinsfile
Labels: lgtm, size/XS, approved

#242 Updating the odf schedule
  hack/jjb_template.jinja2
Labels: lgtm, approved, size/S

#243 Change upgrade related environment vars
  deploy/templates/.deploy-openshift4-powervc.tfvars.template
  deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
  deploy/templates/.deploy-openshift4-powervs.tfvars.template
  jobs/pipelines/powervm/ocp/4.10/daily-ocp4.10-to-4.11-powervm-p8-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.11/daily-ocp4.11-to-4.12-powervm-p8-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/daily-ocp4.13-powervm-p9-vscsi/Jenkinsfile
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, size/S
