Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2023-12, with the labels that each got.

#311 odf-4.15
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-4b/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-4c/Jenkinsfile
  vars/odfRunSetupScript.groovy
Labels: approved, size/XXL

#312 disabling vault by default
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-4b/Jenkinsfile
  jobs/pipelines/powervm/odf/4.15/daily-odf4.15-powervm-p9-tier-4c/Jenkinsfile
Labels: approved

#313 remove custom job
  jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4-deploy-1/Jenkinsfile
Labels: approved, size/XL

#314 Revert "remove custom job"
  jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4-deploy-1/Jenkinsfile
Labels: approved, size/XL

#315 fixing jinja2 template
  hack/jjb_template.jinja2
Labels: approved

#316 Revert the changes.
  jobs/pipelines/powervs/ipi/4.11/daily-ipi4.11-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.11/daily-ipi4.11-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.11/daily-ipi4.11-powervs-toronto01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.12/daily-ipi4.12-powervs-sydney05/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.13/daily-ipi4.13-powervs-sydney05/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-london06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-montreal01/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-osaka21/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-sydney05/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.14/daily-ipi4.14-powervs-tokyo04-1/Jenkinsfile
Labels: lgtm, approved, size/S

#317 reducing number of reruns
  vars/setupCommonEnvironmentVariables.groovy
Labels: size/XS, approved
