Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2023-11, with the labels that each got.

#300 Enable kdump in ocp 4.14 and 4.15 daily jobs on PowerVC and PowerVS
  deploy/Makefile
  deploy/templates/.deploy-openshift4-powervc.tfvars.template
  deploy/templates/.deploy-openshift4-powervs-script.tfvars.template
  jobs/pipelines/powervm/ocp/4.14/daily-ocp4.14-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.15/daily-ocp4.15-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp/4.14/daily-ocp4.14-powervs-script-p9-min/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  scripts/kdump/kdump_gather_logs.sh
  vars/gatherKdumpLogs.groovy
Labels: lgtm, approved, size/L

#305 Disabled influx db update temporarly
  jobs/pipelines/powervm/ocp/4.12/weekly-ocp4.12-to-4.13-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.14/daily-ocp4.14-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-sdn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-sriov/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-powervm-p9-vscsi/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-to-4.15-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.15/daily-ocp4.15-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervs/ocp/4.14/daily-ocp4.14-powervs-script-p9-min/Jenkinsfile
Labels: lgtm, approved, size/S

#304 Enabling 4.14 z-stream jobs for PowerVC and PowerVS
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-direct-current-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-p9-trigger-job/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-current-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-ocp4x-powervs-london06-p9-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ocp/zstreams/zstream-powervs-trigger-job/Jenkinsfile
Labels: lgtm, approved, size/S, needs-ok-to-test

#306 Added fix for docker push temporarily
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  scripts/mirror-images.sh
Labels: lgtm, approved, size/M
