Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2024-09, with the labels that each got.

#339 Enable compliance operator e2e on custom ci job
  jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4.x-powervm-p9-deploy-operator-tests/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  scripts/operator/compliance_operator.sh
Labels: lgtm, approved, size/M

#341 Adding tier 4a job
  jobs/pipelines/powervm/odf/4.17/odf4.17-powervm-p9-tier-4a/Jenkinsfile
Labels: lgtm, approved, size/L

#342 Add IPI cleanup scheduled job and fix job failures.
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-to-4.17-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
  jobs/pipelines/utility-jobs/powervs-ipi-cleanup-job/Jenkinsfile
  scripts/cleanup-ipi-resources.sh
Labels: lgtm, approved, size/L

#343 PowerVM and PowerVS: Enabling ocp 4.18 jobs
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.18/daily-ocp4.18-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.18/weekly-ocp4.17-to-4.18-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.18/weekly-ocp4.18-powervm-p9-npiv/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.18/weekly-ocp4.18-powervm-p9-sriov/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.18/weekly-ocp4.18-powervm-p9-verification/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.18/weekly-ocp4.18-powervm-p9-vscsi-multipath/Jenkinsfile
  jobs/pipelines/powervm/poll-powervc-images/Jenkinsfile
  jobs/pipelines/powervs/ocp/4.18/daily-ocp4.18-powervs-script-p9-min/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
  jobs/pipelines/utility-jobs/powervs-cleanup-job/Jenkinsfile
  jobs/pipelines/utility-jobs/powervs-ipi-cleanup-job/Jenkinsfile
  scripts/operator/compliance_operator.sh
  vars/cleanupOcp4Cluster.groovy
  vars/initializeEnvironment.groovy
  vars/setupCommonEnvironmentVariables.groovy
Labels: lgtm, approved, size/XXL
