Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2024-07, with the labels that each got.

#333 Enable zstream jobs on on-prem
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.12/weekly-ocp4.12-to-4.13-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-to-4.16-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4.x-powervm-p9-deploy-croo-metallb/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-ocp4x-p8-min-current-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-ocp4x-p8-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-ocp4x-p8-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p8-min/zstream-p8-trigger-job/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-current-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-direct-deploy/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min/zstream-p9-trigger-job/Jenkinsfile
  scripts/capture-artifacts-ocp4.sh
  scripts/cron.sh
Labels: lgtm, approved, size/L

#336 Adding 4.17 odf jobs
  jobs/pipelines/powervm/odf/4.17/odf4.17-powervm-p9-tier-1/Jenkinsfile
  jobs/pipelines/powervm/odf/4.17/odf4.17-powervm-p9-tier-2/Jenkinsfile
  jobs/pipelines/powervm/odf/4.17/odf4.17-powervm-p9-tier-3/Jenkinsfile
  jobs/pipelines/powervm/odf/4.17/odf4.17-powervm-p9-tier-4b/Jenkinsfile
  jobs/pipelines/powervm/odf/4.17/odf4.17-powervm-p9-tier-4c/Jenkinsfile
  vars/odfRunSetupScript.groovy
Labels: lgtm, approved, size/XXL

#337 Updated the e2e process code for filtering the latest Junit_e2e*.xml files.
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.17/weekly-ocp4.17-powervm-p9-npiv/Jenkinsfile
  vars/processE2eResults.groovy
Labels: lgtm, approved, size/S
