Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2024-06, with the labels that each got.

#329 Adding 4.16 IPI Jobs
  hack/jjb_template.jinja2
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-frankfurt1/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-frankfurt2/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-madrid02/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-madrid04/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-saopaulo04/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-washingtondc06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.16/daily-ipi4.16-powervs-washingtondc07/Jenkinsfile
  jobs/pipelines/powervs/poll-powervs-images/Jenkinsfile
Labels: lgtm, approved, size/XXL

#330 Removing the sdn 4.15 and 4.16 jobs and fix the few issues
  hack/jjb_template.jinja2
  jobs/pipelines/mirror-openshift-release/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.12/weekly-ocp4.12-to-4.13-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-to-4.14-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-powervm-p9-sdn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.15/weekly-ocp4.15-to-4.16-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-sdn-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/custom-powervm-jobs/custom-ocp4.x-powervm-p9-deploy-croo-metallb/Jenkinsfile
Labels: lgtm, approved, size/L

#331 Get ceph status
  scripts/odf/odf-build-info.sh
Labels: lgtm, size/XS, approved
