Repository ppc64le-cloud/jenkins-infra, pull requests merged in 2024-04, with the labels that each got.

#323 Remove local images after pushing them to registry and change IPI agent.
  jobs/pipelines/powervm/ocp/4.12/weekly-ocp4.12-to-4.13-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-powervm-p9-min/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.13/weekly-ocp4.13-to-4.14-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervm/ocp/4.14/weekly-ocp4.14-to-4.15-powervm-p9-min-upgrade/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-madrid02/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-washingtondc06/Jenkinsfile
  jobs/pipelines/powervs/ipi/4.15/daily-ipi4.15-powervs-washingtondc07/Jenkinsfile
  scripts/mirror-images.sh
Labels: lgtm, approved, size/M

#324 Updating 4.15 branch info
  vars/odfRunSetupScript.groovy
Labels: lgtm, size/XS, approved

#325 Updated go version in the PowerVS 4.16 ocp job and the SCG ID for PowerVC 4.16 vscsi job.
  hack/jjb_template.jinja2
  jobs/pipelines/powervm/ocp/4.16/weekly-ocp4.16-powervm-p9-vscsi/Jenkinsfile
  jobs/pipelines/powervs/ocp/4.16/daily-ocp4.16-powervs-script-p9-min/Jenkinsfile
  scripts/verification.sh
Labels: lgtm, approved, size/S
